services:
  - type: web
    name: carebridge-health
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: FLASK_DEBUG
        value: "false"
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
